// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dnsmessage.proto

/*
Package dnsmessage is a generated protocol buffer package.

It is generated from these files:
	dnsmessage.proto

It has these top-level messages:
	PBDNSMessage
*/
package dnsmessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PBDNSMessage_Type int32

const (
	PBDNSMessage_DNSQueryType            PBDNSMessage_Type = 1
	PBDNSMessage_DNSResponseType         PBDNSMessage_Type = 2
	PBDNSMessage_DNSOutgoingQueryType    PBDNSMessage_Type = 3
	PBDNSMessage_DNSIncomingResponseType PBDNSMessage_Type = 4
)

var PBDNSMessage_Type_name = map[int32]string{
	1: "DNSQueryType",
	2: "DNSResponseType",
	3: "DNSOutgoingQueryType",
	4: "DNSIncomingResponseType",
}
var PBDNSMessage_Type_value = map[string]int32{
	"DNSQueryType":            1,
	"DNSResponseType":         2,
	"DNSOutgoingQueryType":    3,
	"DNSIncomingResponseType": 4,
}

func (x PBDNSMessage_Type) Enum() *PBDNSMessage_Type {
	p := new(PBDNSMessage_Type)
	*p = x
	return p
}
func (x PBDNSMessage_Type) String() string {
	return proto.EnumName(PBDNSMessage_Type_name, int32(x))
}
func (x *PBDNSMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PBDNSMessage_Type_value, data, "PBDNSMessage_Type")
	if err != nil {
		return err
	}
	*x = PBDNSMessage_Type(value)
	return nil
}
func (PBDNSMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type PBDNSMessage_SocketFamily int32

const (
	PBDNSMessage_INET  PBDNSMessage_SocketFamily = 1
	PBDNSMessage_INET6 PBDNSMessage_SocketFamily = 2
)

var PBDNSMessage_SocketFamily_name = map[int32]string{
	1: "INET",
	2: "INET6",
}
var PBDNSMessage_SocketFamily_value = map[string]int32{
	"INET":  1,
	"INET6": 2,
}

func (x PBDNSMessage_SocketFamily) Enum() *PBDNSMessage_SocketFamily {
	p := new(PBDNSMessage_SocketFamily)
	*p = x
	return p
}
func (x PBDNSMessage_SocketFamily) String() string {
	return proto.EnumName(PBDNSMessage_SocketFamily_name, int32(x))
}
func (x *PBDNSMessage_SocketFamily) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PBDNSMessage_SocketFamily_value, data, "PBDNSMessage_SocketFamily")
	if err != nil {
		return err
	}
	*x = PBDNSMessage_SocketFamily(value)
	return nil
}
func (PBDNSMessage_SocketFamily) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type PBDNSMessage_SocketProtocol int32

const (
	PBDNSMessage_UDP PBDNSMessage_SocketProtocol = 1
	PBDNSMessage_TCP PBDNSMessage_SocketProtocol = 2
)

var PBDNSMessage_SocketProtocol_name = map[int32]string{
	1: "UDP",
	2: "TCP",
}
var PBDNSMessage_SocketProtocol_value = map[string]int32{
	"UDP": 1,
	"TCP": 2,
}

func (x PBDNSMessage_SocketProtocol) Enum() *PBDNSMessage_SocketProtocol {
	p := new(PBDNSMessage_SocketProtocol)
	*p = x
	return p
}
func (x PBDNSMessage_SocketProtocol) String() string {
	return proto.EnumName(PBDNSMessage_SocketProtocol_name, int32(x))
}
func (x *PBDNSMessage_SocketProtocol) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PBDNSMessage_SocketProtocol_value, data, "PBDNSMessage_SocketProtocol")
	if err != nil {
		return err
	}
	*x = PBDNSMessage_SocketProtocol(value)
	return nil
}
func (PBDNSMessage_SocketProtocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 2}
}

type PBDNSMessage_PolicyType int32

const (
	PBDNSMessage_UNKNOWN    PBDNSMessage_PolicyType = 1
	PBDNSMessage_QNAME      PBDNSMessage_PolicyType = 2
	PBDNSMessage_CLIENTIP   PBDNSMessage_PolicyType = 3
	PBDNSMessage_RESPONSEIP PBDNSMessage_PolicyType = 4
	PBDNSMessage_NSDNAME    PBDNSMessage_PolicyType = 5
	PBDNSMessage_NSIP       PBDNSMessage_PolicyType = 6
)

var PBDNSMessage_PolicyType_name = map[int32]string{
	1: "UNKNOWN",
	2: "QNAME",
	3: "CLIENTIP",
	4: "RESPONSEIP",
	5: "NSDNAME",
	6: "NSIP",
}
var PBDNSMessage_PolicyType_value = map[string]int32{
	"UNKNOWN":    1,
	"QNAME":      2,
	"CLIENTIP":   3,
	"RESPONSEIP": 4,
	"NSDNAME":    5,
	"NSIP":       6,
}

func (x PBDNSMessage_PolicyType) Enum() *PBDNSMessage_PolicyType {
	p := new(PBDNSMessage_PolicyType)
	*p = x
	return p
}
func (x PBDNSMessage_PolicyType) String() string {
	return proto.EnumName(PBDNSMessage_PolicyType_name, int32(x))
}
func (x *PBDNSMessage_PolicyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PBDNSMessage_PolicyType_value, data, "PBDNSMessage_PolicyType")
	if err != nil {
		return err
	}
	*x = PBDNSMessage_PolicyType(value)
	return nil
}
func (PBDNSMessage_PolicyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

type PBDNSMessage struct {
	Type                    *PBDNSMessage_Type           `protobuf:"varint,1,req,name=type,enum=PBDNSMessage_Type" json:"type,omitempty"`
	MessageId               []byte                       `protobuf:"bytes,2,opt,name=messageId" json:"messageId,omitempty"`
	ServerIdentity          []byte                       `protobuf:"bytes,3,opt,name=serverIdentity" json:"serverIdentity,omitempty"`
	SocketFamily            *PBDNSMessage_SocketFamily   `protobuf:"varint,4,opt,name=socketFamily,enum=PBDNSMessage_SocketFamily" json:"socketFamily,omitempty"`
	SocketProtocol          *PBDNSMessage_SocketProtocol `protobuf:"varint,5,opt,name=socketProtocol,enum=PBDNSMessage_SocketProtocol" json:"socketProtocol,omitempty"`
	From                    []byte                       `protobuf:"bytes,6,opt,name=from" json:"from,omitempty"`
	To                      []byte                       `protobuf:"bytes,7,opt,name=to" json:"to,omitempty"`
	InBytes                 *uint64                      `protobuf:"varint,8,opt,name=inBytes" json:"inBytes,omitempty"`
	TimeSec                 *uint32                      `protobuf:"varint,9,opt,name=timeSec" json:"timeSec,omitempty"`
	TimeUsec                *uint32                      `protobuf:"varint,10,opt,name=timeUsec" json:"timeUsec,omitempty"`
	Id                      *uint32                      `protobuf:"varint,11,opt,name=id" json:"id,omitempty"`
	Question                *PBDNSMessage_DNSQuestion    `protobuf:"bytes,12,opt,name=question" json:"question,omitempty"`
	Response                *PBDNSMessage_DNSResponse    `protobuf:"bytes,13,opt,name=response" json:"response,omitempty"`
	OriginalRequestorSubnet []byte                       `protobuf:"bytes,14,opt,name=originalRequestorSubnet" json:"originalRequestorSubnet,omitempty"`
	RequestorId             *string                      `protobuf:"bytes,15,opt,name=requestorId" json:"requestorId,omitempty"`
	InitialRequestId        []byte                       `protobuf:"bytes,16,opt,name=initialRequestId" json:"initialRequestId,omitempty"`
	DeviceId                []byte                       `protobuf:"bytes,17,opt,name=deviceId" json:"deviceId,omitempty"`
	XXX_unrecognized        []byte                       `json:"-"`
}

func (m *PBDNSMessage) Reset()                    { *m = PBDNSMessage{} }
func (m *PBDNSMessage) String() string            { return proto.CompactTextString(m) }
func (*PBDNSMessage) ProtoMessage()               {}
func (*PBDNSMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PBDNSMessage) GetType() PBDNSMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PBDNSMessage_DNSQueryType
}

func (m *PBDNSMessage) GetMessageId() []byte {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *PBDNSMessage) GetServerIdentity() []byte {
	if m != nil {
		return m.ServerIdentity
	}
	return nil
}

func (m *PBDNSMessage) GetSocketFamily() PBDNSMessage_SocketFamily {
	if m != nil && m.SocketFamily != nil {
		return *m.SocketFamily
	}
	return PBDNSMessage_INET
}

func (m *PBDNSMessage) GetSocketProtocol() PBDNSMessage_SocketProtocol {
	if m != nil && m.SocketProtocol != nil {
		return *m.SocketProtocol
	}
	return PBDNSMessage_UDP
}

func (m *PBDNSMessage) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *PBDNSMessage) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *PBDNSMessage) GetInBytes() uint64 {
	if m != nil && m.InBytes != nil {
		return *m.InBytes
	}
	return 0
}

func (m *PBDNSMessage) GetTimeSec() uint32 {
	if m != nil && m.TimeSec != nil {
		return *m.TimeSec
	}
	return 0
}

func (m *PBDNSMessage) GetTimeUsec() uint32 {
	if m != nil && m.TimeUsec != nil {
		return *m.TimeUsec
	}
	return 0
}

func (m *PBDNSMessage) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PBDNSMessage) GetQuestion() *PBDNSMessage_DNSQuestion {
	if m != nil {
		return m.Question
	}
	return nil
}

func (m *PBDNSMessage) GetResponse() *PBDNSMessage_DNSResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *PBDNSMessage) GetOriginalRequestorSubnet() []byte {
	if m != nil {
		return m.OriginalRequestorSubnet
	}
	return nil
}

func (m *PBDNSMessage) GetRequestorId() string {
	if m != nil && m.RequestorId != nil {
		return *m.RequestorId
	}
	return ""
}

func (m *PBDNSMessage) GetInitialRequestId() []byte {
	if m != nil {
		return m.InitialRequestId
	}
	return nil
}

func (m *PBDNSMessage) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

type PBDNSMessage_DNSQuestion struct {
	QName            *string `protobuf:"bytes,1,opt,name=qName" json:"qName,omitempty"`
	QType            *uint32 `protobuf:"varint,2,opt,name=qType" json:"qType,omitempty"`
	QClass           *uint32 `protobuf:"varint,3,opt,name=qClass" json:"qClass,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDNSMessage_DNSQuestion) Reset()                    { *m = PBDNSMessage_DNSQuestion{} }
func (m *PBDNSMessage_DNSQuestion) String() string            { return proto.CompactTextString(m) }
func (*PBDNSMessage_DNSQuestion) ProtoMessage()               {}
func (*PBDNSMessage_DNSQuestion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *PBDNSMessage_DNSQuestion) GetQName() string {
	if m != nil && m.QName != nil {
		return *m.QName
	}
	return ""
}

func (m *PBDNSMessage_DNSQuestion) GetQType() uint32 {
	if m != nil && m.QType != nil {
		return *m.QType
	}
	return 0
}

func (m *PBDNSMessage_DNSQuestion) GetQClass() uint32 {
	if m != nil && m.QClass != nil {
		return *m.QClass
	}
	return 0
}

type PBDNSMessage_DNSResponse struct {
	Rcode             *uint32                           `protobuf:"varint,1,opt,name=rcode" json:"rcode,omitempty"`
	Rrs               []*PBDNSMessage_DNSResponse_DNSRR `protobuf:"bytes,2,rep,name=rrs" json:"rrs,omitempty"`
	AppliedPolicy     *string                           `protobuf:"bytes,3,opt,name=appliedPolicy" json:"appliedPolicy,omitempty"`
	Tags              []string                          `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	QueryTimeSec      *uint32                           `protobuf:"varint,5,opt,name=queryTimeSec" json:"queryTimeSec,omitempty"`
	QueryTimeUsec     *uint32                           `protobuf:"varint,6,opt,name=queryTimeUsec" json:"queryTimeUsec,omitempty"`
	AppliedPolicyType *PBDNSMessage_PolicyType          `protobuf:"varint,7,opt,name=appliedPolicyType,enum=PBDNSMessage_PolicyType" json:"appliedPolicyType,omitempty"`
	XXX_unrecognized  []byte                            `json:"-"`
}

func (m *PBDNSMessage_DNSResponse) Reset()                    { *m = PBDNSMessage_DNSResponse{} }
func (m *PBDNSMessage_DNSResponse) String() string            { return proto.CompactTextString(m) }
func (*PBDNSMessage_DNSResponse) ProtoMessage()               {}
func (*PBDNSMessage_DNSResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *PBDNSMessage_DNSResponse) GetRcode() uint32 {
	if m != nil && m.Rcode != nil {
		return *m.Rcode
	}
	return 0
}

func (m *PBDNSMessage_DNSResponse) GetRrs() []*PBDNSMessage_DNSResponse_DNSRR {
	if m != nil {
		return m.Rrs
	}
	return nil
}

func (m *PBDNSMessage_DNSResponse) GetAppliedPolicy() string {
	if m != nil && m.AppliedPolicy != nil {
		return *m.AppliedPolicy
	}
	return ""
}

func (m *PBDNSMessage_DNSResponse) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PBDNSMessage_DNSResponse) GetQueryTimeSec() uint32 {
	if m != nil && m.QueryTimeSec != nil {
		return *m.QueryTimeSec
	}
	return 0
}

func (m *PBDNSMessage_DNSResponse) GetQueryTimeUsec() uint32 {
	if m != nil && m.QueryTimeUsec != nil {
		return *m.QueryTimeUsec
	}
	return 0
}

func (m *PBDNSMessage_DNSResponse) GetAppliedPolicyType() PBDNSMessage_PolicyType {
	if m != nil && m.AppliedPolicyType != nil {
		return *m.AppliedPolicyType
	}
	return PBDNSMessage_UNKNOWN
}

type PBDNSMessage_DNSResponse_DNSRR struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type             *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Class            *uint32 `protobuf:"varint,3,opt,name=class" json:"class,omitempty"`
	Ttl              *uint32 `protobuf:"varint,4,opt,name=ttl" json:"ttl,omitempty"`
	Rdata            []byte  `protobuf:"bytes,5,opt,name=rdata" json:"rdata,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDNSMessage_DNSResponse_DNSRR) Reset()         { *m = PBDNSMessage_DNSResponse_DNSRR{} }
func (m *PBDNSMessage_DNSResponse_DNSRR) String() string { return proto.CompactTextString(m) }
func (*PBDNSMessage_DNSResponse_DNSRR) ProtoMessage()    {}
func (*PBDNSMessage_DNSResponse_DNSRR) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1, 0}
}

func (m *PBDNSMessage_DNSResponse_DNSRR) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PBDNSMessage_DNSResponse_DNSRR) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PBDNSMessage_DNSResponse_DNSRR) GetClass() uint32 {
	if m != nil && m.Class != nil {
		return *m.Class
	}
	return 0
}

func (m *PBDNSMessage_DNSResponse_DNSRR) GetTtl() uint32 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

func (m *PBDNSMessage_DNSResponse_DNSRR) GetRdata() []byte {
	if m != nil {
		return m.Rdata
	}
	return nil
}

func init() {
	proto.RegisterType((*PBDNSMessage)(nil), "PBDNSMessage")
	proto.RegisterType((*PBDNSMessage_DNSQuestion)(nil), "PBDNSMessage.DNSQuestion")
	proto.RegisterType((*PBDNSMessage_DNSResponse)(nil), "PBDNSMessage.DNSResponse")
	proto.RegisterType((*PBDNSMessage_DNSResponse_DNSRR)(nil), "PBDNSMessage.DNSResponse.DNSRR")
	proto.RegisterEnum("PBDNSMessage_Type", PBDNSMessage_Type_name, PBDNSMessage_Type_value)
	proto.RegisterEnum("PBDNSMessage_SocketFamily", PBDNSMessage_SocketFamily_name, PBDNSMessage_SocketFamily_value)
	proto.RegisterEnum("PBDNSMessage_SocketProtocol", PBDNSMessage_SocketProtocol_name, PBDNSMessage_SocketProtocol_value)
	proto.RegisterEnum("PBDNSMessage_PolicyType", PBDNSMessage_PolicyType_name, PBDNSMessage_PolicyType_value)
}

func init() { proto.RegisterFile("dnsmessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5b, 0x6b, 0xdb, 0x4c,
	0x10, 0x45, 0x17, 0xdf, 0xc6, 0xb2, 0xa2, 0xec, 0x17, 0xbe, 0x6c, 0xdd, 0x40, 0x85, 0x5b, 0x82,
	0xe8, 0x43, 0xa0, 0x86, 0x96, 0x3e, 0x15, 0x9a, 0xd8, 0x01, 0xd1, 0x46, 0x51, 0x56, 0x0e, 0xa5,
	0x8f, 0xaa, 0xb4, 0x35, 0x4b, 0x6d, 0xc9, 0x96, 0xd6, 0x01, 0xff, 0x84, 0x3e, 0xf6, 0x1f, 0x97,
	0x1d, 0xf9, 0xa6, 0xa4, 0x79, 0x9b, 0x73, 0xe6, 0xcc, 0xec, 0xce, 0xd1, 0x68, 0xc1, 0x49, 0xb3,
	0x72, 0xce, 0xcb, 0x32, 0x9e, 0xf2, 0x8b, 0x45, 0x91, 0xcb, 0x7c, 0xf0, 0xbb, 0x0b, 0x56, 0x78,
	0x39, 0x0a, 0xa2, 0x9b, 0x8a, 0x26, 0xe7, 0x60, 0xca, 0xf5, 0x82, 0x53, 0xcd, 0xd5, 0x3d, 0x7b,
	0x48, 0x2e, 0x0e, 0x93, 0x17, 0x93, 0xf5, 0x82, 0x33, 0xcc, 0x93, 0x33, 0xe8, 0x6c, 0x3a, 0xf9,
	0x29, 0xd5, 0x5d, 0xcd, 0xb3, 0xd8, 0x9e, 0x20, 0xe7, 0x60, 0x97, 0xbc, 0x78, 0xe0, 0x85, 0x9f,
	0xf2, 0x4c, 0x0a, 0xb9, 0xa6, 0x06, 0x4a, 0x1e, 0xb1, 0xe4, 0x13, 0x58, 0x65, 0x9e, 0xfc, 0xe2,
	0xf2, 0x3a, 0x9e, 0x8b, 0xd9, 0x9a, 0x9a, 0xae, 0xe6, 0xd9, 0xc3, 0x7e, 0xfd, 0xd4, 0xe8, 0x40,
	0xc1, 0x6a, 0x7a, 0x32, 0x02, 0xbb, 0xc2, 0xa1, 0x9a, 0x26, 0xc9, 0x67, 0xb4, 0x81, 0x1d, 0xce,
	0xfe, 0xd5, 0x61, 0xab, 0x61, 0x8f, 0x6a, 0x08, 0x01, 0xf3, 0x67, 0x91, 0xcf, 0x69, 0x13, 0xef,
	0x88, 0x31, 0xb1, 0x41, 0x97, 0x39, 0x6d, 0x21, 0xa3, 0xcb, 0x9c, 0x50, 0x68, 0x89, 0xec, 0x72,
	0x2d, 0x79, 0x49, 0xdb, 0xae, 0xe6, 0x99, 0x6c, 0x0b, 0x55, 0x46, 0x8a, 0x39, 0x8f, 0x78, 0x42,
	0x3b, 0xae, 0xe6, 0xf5, 0xd8, 0x16, 0x92, 0x3e, 0xb4, 0x55, 0x78, 0x5f, 0xf2, 0x84, 0x02, 0xa6,
	0x76, 0x58, 0xf5, 0x17, 0x29, 0xed, 0x22, 0xab, 0x8b, 0x94, 0xbc, 0x87, 0xf6, 0x72, 0xc5, 0x4b,
	0x29, 0xf2, 0x8c, 0x5a, 0xae, 0xe6, 0x75, 0x87, 0x2f, 0xea, 0x33, 0x8c, 0x82, 0xe8, 0x6e, 0x23,
	0x60, 0x3b, 0xa9, 0x2a, 0x2b, 0x78, 0xb9, 0xc8, 0xb3, 0x92, 0xd3, 0xde, 0x33, 0x65, 0x6c, 0x23,
	0x60, 0x3b, 0x29, 0xf9, 0x08, 0xa7, 0x79, 0x21, 0xa6, 0x22, 0x8b, 0x67, 0x8c, 0x63, 0xb3, 0xbc,
	0x88, 0x56, 0x3f, 0x32, 0x2e, 0xa9, 0x8d, 0x23, 0x3f, 0x97, 0x26, 0x2e, 0x74, 0x8b, 0x2d, 0xe5,
	0xa7, 0xf4, 0xc8, 0xd5, 0xbc, 0x0e, 0x3b, 0xa4, 0xc8, 0x5b, 0x70, 0x44, 0x26, 0xa4, 0xd8, 0xd5,
	0xfa, 0x29, 0x75, 0xb0, 0xe9, 0x13, 0x5e, 0x39, 0x94, 0xf2, 0x07, 0x91, 0xa8, 0x25, 0x3a, 0x46,
	0xcd, 0x0e, 0xf7, 0xef, 0xa0, 0x7b, 0x30, 0x33, 0x39, 0x81, 0xc6, 0x32, 0x88, 0xe7, 0x6a, 0x33,
	0xd5, 0x91, 0x15, 0x40, 0x56, 0x6d, 0x25, 0xae, 0x60, 0x8f, 0x55, 0x80, 0xfc, 0x0f, 0xcd, 0xe5,
	0xd5, 0x2c, 0x2e, 0x4b, 0x5c, 0xbb, 0x1e, 0xdb, 0xa0, 0xfe, 0x1f, 0x03, 0x7b, 0x6e, 0x0d, 0x51,
	0xd5, 0x45, 0x92, 0xa7, 0x55, 0xcf, 0x1e, 0xab, 0x00, 0x79, 0x07, 0x46, 0x51, 0x94, 0x54, 0x77,
	0x0d, 0xaf, 0x3b, 0x7c, 0xf5, 0xac, 0x9d, 0x18, 0x33, 0xa6, 0xb4, 0xe4, 0x0d, 0xf4, 0xe2, 0xc5,
	0x62, 0x26, 0x78, 0x1a, 0xe6, 0x33, 0x91, 0x54, 0xeb, 0xde, 0x61, 0x75, 0x52, 0xed, 0x99, 0x8c,
	0xa7, 0x25, 0x35, 0x5d, 0xc3, 0xeb, 0x30, 0x8c, 0xc9, 0x00, 0xac, 0xe5, 0x8a, 0x17, 0xeb, 0xc9,
	0x66, 0x85, 0x1a, 0x78, 0x93, 0x1a, 0xa7, 0xba, 0xef, 0x30, 0x2e, 0x53, 0x13, 0x45, 0x75, 0x92,
	0x5c, 0xc3, 0x71, 0xed, 0x38, 0xb4, 0xa5, 0x85, 0xbf, 0x03, 0xad, 0x0f, 0xb1, 0xcf, 0xb3, 0xa7,
	0x25, 0xfd, 0x39, 0x34, 0x70, 0x32, 0x75, 0xdd, 0x6c, 0x6f, 0x38, 0xc6, 0x38, 0xc2, 0xde, 0xee,
	0xea, 0x29, 0x38, 0x81, 0x46, 0x72, 0x60, 0x76, 0x05, 0x88, 0x03, 0x86, 0x94, 0x33, 0xfc, 0xa3,
	0x7b, 0x4c, 0x85, 0xe8, 0x76, 0x1a, 0xcb, 0x18, 0x67, 0xb4, 0x58, 0x05, 0x06, 0x29, 0x98, 0xf8,
	0xcd, 0x1c, 0xb0, 0xaa, 0xcf, 0x5d, 0xe0, 0x35, 0x1c, 0x8d, 0xfc, 0x07, 0x47, 0x07, 0x76, 0x23,
	0xa9, 0x13, 0x0a, 0x27, 0xa3, 0x20, 0xba, 0x5d, 0xc9, 0x69, 0x2e, 0xb2, 0xe9, 0x5e, 0x6e, 0x90,
	0x97, 0x70, 0x3a, 0x0a, 0x22, 0x3f, 0x4b, 0xf2, 0xb9, 0xc8, 0xa6, 0xb5, 0x32, 0x73, 0xf0, 0x1a,
	0xac, 0xc3, 0x67, 0x84, 0xb4, 0xc1, 0xf4, 0x83, 0xf1, 0xc4, 0xd1, 0x48, 0x07, 0x1a, 0x2a, 0xfa,
	0xe0, 0xe8, 0x83, 0x01, 0xd8, 0xf5, 0x97, 0x82, 0xb4, 0xc0, 0xb8, 0x1f, 0x85, 0x8e, 0xa6, 0x82,
	0xc9, 0x55, 0xe8, 0xe8, 0x83, 0xef, 0x00, 0x7b, 0xaf, 0x48, 0x17, 0x5a, 0xf7, 0xc1, 0x97, 0xe0,
	0xf6, 0x5b, 0x50, 0x75, 0xba, 0x0b, 0x3e, 0xdf, 0x8c, 0x1d, 0x9d, 0x58, 0xd0, 0xbe, 0xfa, 0xea,
	0x8f, 0x83, 0x89, 0x1f, 0x3a, 0x06, 0xb1, 0x01, 0xd8, 0x38, 0x0a, 0x6f, 0x83, 0x68, 0xec, 0x87,
	0x8e, 0xa9, 0xaa, 0x82, 0x68, 0x84, 0xd2, 0x86, 0xba, 0x49, 0x10, 0xf9, 0xa1, 0xd3, 0xfc, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xad, 0x15, 0x67, 0xcb, 0x9e, 0x05, 0x00, 0x00,
}
